# Generated by Django 5.0.6 on 2024-08-29 05:13

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_advuser_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
