# Generated by Django 5.0.6 on 2024-07-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(max_length=32, verbose_name='Участники путешествия')),
            ],
        ),
        migrations.RemoveField(
            model_name='journeyalbum',
            name='person_number',
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_descr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание альбома, эмоции'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать альбом'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_name',
            field=models.CharField(max_length=32, verbose_name='Имя альбома'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Имя альбома в адресной строке'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='j_month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Месяц путешествия'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='j_place',
            field=models.CharField(max_length=64, verbose_name='Место путешествия'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='j_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.typejourney', verbose_name='Характер (тип) путешествия'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='j_year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Год путешествия'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='album.journeyalbum', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_descr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фото, эмоции'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_file',
            field=models.ImageField(upload_to='img', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_name',
            field=models.CharField(max_length=36, verbose_name='Имя фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Имя фото в адресной строке'),
        ),
        migrations.AlterField(
            model_name='typejourney',
            name='j_type_descr',
            field=models.CharField(max_length=256, verbose_name='Описание типа путешествия'),
        ),
        migrations.AlterField(
            model_name='typejourney',
            name='j_type_name',
            field=models.CharField(max_length=32, verbose_name='Тип путешествия'),
        ),
        migrations.AddField(
            model_name='journeyalbum',
            name='travel_participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.travelparticipants'),
        ),
    ]
