# Generated by Django 5.0.6 on 2024-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_travelparticipants_remove_journeyalbum_person_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ph_file',
            field=models.ImageField(upload_to='img/photos', verbose_name='Файл'),
        ),
    ]
