# Generated by Django 5.0.6 on 2024-08-29 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_journeyalbum_a_author_photo_ph_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_is_active',
            field=models.BooleanField(default=False, verbose_name='Отображать альбом'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='travel_participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.travelparticipants', verbose_name='Участники путешествия'),
        ),
    ]
