# Generated by Django 4.2.16 on 2024-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_journeyalbum_a_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ph_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/photos/thumbnails', verbose_name='Миниатюра'),
        ),
    ]
