# Generated by Django 4.2.16 on 2024-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_photo_ph_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyalbum',
            name='a_descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание альбома, эмоции'),
        ),
        migrations.AddField(
            model_name='journeyalbum',
            name='a_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание альбома, эмоции'),
        ),
        migrations.AddField(
            model_name='journeyalbum',
            name='a_name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя альбома'),
        ),
        migrations.AddField(
            model_name='journeyalbum',
            name='a_name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя альбома'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ph_descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фото, эмоции'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ph_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фото, эмоции'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ph_name_en',
            field=models.CharField(max_length=36, null=True, verbose_name='Имя фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ph_name_ru',
            field=models.CharField(max_length=36, null=True, verbose_name='Имя фото'),
        ),
        migrations.AddField(
            model_name='travelparticipants',
            name='participants_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Участники путешествия'),
        ),
        migrations.AddField(
            model_name='travelparticipants',
            name='participants_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Участники путешествия'),
        ),
        migrations.AddField(
            model_name='typejourney',
            name='j_type_descr_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Описание типа путешествия'),
        ),
        migrations.AddField(
            model_name='typejourney',
            name='j_type_descr_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Описание типа путешествия'),
        ),
        migrations.AddField(
            model_name='typejourney',
            name='j_type_name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Тип путешествия'),
        ),
        migrations.AddField(
            model_name='typejourney',
            name='j_type_name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Тип путешествия'),
        ),
    ]
