# Generated by Django 4.2.16 on 2024-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_journeyalbum_a_descr_en_journeyalbum_a_descr_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ph_name',
            field=models.CharField(max_length=80, verbose_name='Имя фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ph_name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя фото'),
        ),
    ]
