# Generated by Django 4.2.16 on 2024-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_alter_photo_ph_name_alter_photo_ph_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_name',
            field=models.CharField(max_length=80, verbose_name='Имя альбома'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя альбома'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя альбома'),
        ),
        migrations.AlterField(
            model_name='journeyalbum',
            name='a_slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='Имя альбома в адресной строке'),
        ),
    ]
